name: Auto Assign PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.payload.pull_request.user.login;

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [author]
            });
